# Basic
title: Blank_佐毅
subtitle: 上海方创金融信息服务股份有限公司 iOS高级开发工程师
#welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: 嗨，我是姚亚杰(@Blank_佐毅)，一名来自中国的 iOS 开发者 。现居上海。         个性签名：认知这个世界，找到自我的定位。
creator: <a href="http://Blank_佐毅">@heartmusicbeat.com</a>

url: "http://vno.onevcat.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge
markdown: kramdown
#redcarpet:
  #extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: 博客
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: 关于, description: My Projects}
    #url: 'http://project.onevcat.com'
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo:

# Social
social:
    weibo: LoveProgramming
    github: summerHearts
    #twitter: onevcat
    #gplus: 107108267983477358170
    mail: summerHearts@163.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
